"""Markdown-to-HTML API server with billing + analytics. Stdlib only. Run: python server.py"""
import http.server, json, re, os, time
from billing import record_call, FREE_TIER_LIMIT
from analytics import log_call, get_stats, daily_report

PORT = 8777

# Load real LTC wallet address from wallet.json (generated by generate_wallet.py)
_WALLET_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "wallet.json")
try:
    with open(_WALLET_FILE) as _f:
        WALLET_ADDRESS = json.load(_f).get("address", "Las7JLihEnYvACUt4jgxqcFcsFZrD3RgVM")
except Exception:
    WALLET_ADDRESS = "Las7JLihEnYvACUt4jgxqcFcsFZrD3RgVM"

def md_to_html(text):
    # Extract code blocks first to protect them
    blocks = []
    def save_block(m):
        blocks.append(m.group(2))
        return f"\x00CODE{len(blocks)-1}\x00"
    text = re.sub(r"```[ \t]*(\w*)\n(.*?)```", save_block, text, flags=re.DOTALL)

    # Escape HTML
    text = text.replace("&", "&").replace("<", "<").replace(">", ">")

    lines = text.split("\n")
    out, in_list = [], False
    for line in lines:
        # Headings
        m = re.match(r"^(#{1,6})\s+(.*)", line)
        if m:
            if in_list: out.append("</ul>"); in_list = False
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{m.group(2)}</h{lvl}>")
            continue
        # Unordered list
        m = re.match(r"^[-*]\s+(.*)", line)
        if m:
            if not in_list: out.append("<ul>"); in_list = True
            out.append(f"<li>{m.group(1)}</li>")
            continue
        if in_list: out.append("</ul>"); in_list = False
        out.append(line)
    if in_list: out.append("</ul>")
    text = "\n".join(out)

    # Inline: bold, italic, links, inline code
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)

    # Restore code blocks
    for i, code in enumerate(blocks):
        text = text.replace(f"\x00CODE{i}\x00", f"<pre><code>{code}</code></pre>")
    return text.strip()

GUIDE = """Markdown-to-HTML API — Usage Guide
=====================================
POST /convert
  Body: raw markdown text (Content-Type: text/plain or application/json {"markdown": "..."})
  Returns: {"html": "<converted html string>"}
  Supported: headings, bold, italic, links, inline/block code, unordered lists.

GET /health  -> {"status": "ok"}
GET /docs    -> this guide

Examples:
  curl -X POST http://localhost:8777/convert -d '# Hello **world**'
  curl http://localhost:8777/health
"""

class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, *a): pass

    def send(self, code, body, ctype="application/json"):
        data = body.encode() if isinstance(body, str) else body
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        client_ip = self.client_address[0]
        t0 = time.time()
        if self.path == "/health":
            self.send(200, json.dumps({"status": "ok"}))
            log_call("/health", client_ip, 200, time.time() - t0)
        elif self.path == "/docs":
            self.send(200, GUIDE, ctype="text/plain")
            log_call("/docs", client_ip, 200, time.time() - t0)
        elif self.path == "/payment":
            self.send(200, json.dumps({
                "wallet_address": WALLET_ADDRESS,
                "currency": "LTC",
                "message": "Send any amount of Litecoin to this address to continue using the API after the free tier."
            }))
            log_call("/payment", client_ip, 200, time.time() - t0)
        elif self.path == "/usage":
            from billing import check_usage
            usage = check_usage(client_ip)
            self.send(200, json.dumps({
                "client": client_ip,
                "calls_made": usage.get("call_count", 0),
                "free_tier_limit": FREE_TIER_LIMIT,
                "remaining": max(FREE_TIER_LIMIT - usage.get("call_count", 0), 0)
            }))
            log_call("/usage", client_ip, 200, time.time() - t0)
        elif self.path == "/stats":
            self.send(200, json.dumps(get_stats()))
            log_call("/stats", client_ip, 200, time.time() - t0)
        else:
            self.send(404, json.dumps({"error": "not found"}))
            log_call(self.path, client_ip, 404, time.time() - t0)

    def do_POST(self):
        if self.path != "/convert":
            self.send(404, json.dumps({"error": "not found"})); return
        client_ip = self.client_address[0]
        t0 = time.time()
        # Billing check
        bill = record_call(client_ip)
        if bill.get("status") == 402:
            self.send(402, json.dumps(bill))
            log_call("/convert", client_ip, 402, time.time() - t0)
            return
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length).decode("utf-8", errors="replace")
        if self.headers.get("Content-Type", "").startswith("application/json"):
            try: md = json.loads(raw).get("markdown", raw)
            except Exception: md = raw
        else:
            md = raw
        html = md_to_html(md)
        self.send(200, json.dumps({"html": html, "billing": bill}))
        log_call("/convert", client_ip, 200, time.time() - t0)

if __name__ == "__main__":
    print(f"Markdown-to-HTML API on http://localhost:{PORT}")
    http.server.HTTPServer(("0.0.0.0", PORT), Handler).serve_forever()
